# Generated by Django 4.0.2 on 2022-04-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_contact_address_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='place',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
